<?php
$station = "722260";
$date = array("2021-01-26", "2021-01-26", "2021-01-26");
$time = array("12:14:43", "12:14:44", "12:14:45");
$temperature = array("-8.9", "7", "8");
$dewPoint = array("-12.6", "-8.6", "-1.3");
$stationLevelPressure = array("1012.8", "1012.8", "1012.8");
$seaLevelPressure = array("1020.6", "1020.6", "1020.6");
$visibility = array("15.6", "15.6", "15.6");
$windSpeed = array("9.2", "9.2", "9.2");
$percipitation = array("0.27", "0.27", "0.27");
$snowDrop = array("0.0", "0.0", "0.0");
$freeze = array("true", "true", "true");
$rain = array("true", "true", "true");
$snow = array("true", "true", "true");
$hail = array("true", "true", "true");
$thunder = array("true", "true", "true");
$tornado = array("true", "true", "true");
$cloudCoverage = array("79.4", "79.4", "79.4");
$windDirection = array("287", "287", "287");

echo "{";
echo "\"Station\":", json_encode($station), ",";
echo "\"Date\":", json_encode($date), ",";
echo "\"Time\":", json_encode($time), ",";
echo "\"Temperature\":", json_encode($temperature),",";
echo "\"DewPoint\":", json_encode($dewPoint), ",";
echo "\"StationLevelPressure\":", json_encode($stationLevelPressure), ",";
echo "\"SeaLevelPressure\":", json_encode($seaLevelPressure), ",";
echo "\"Visibility\":", json_encode($visibility), ",";
echo "\"WindSpeed\":", json_encode($windSpeed), ",";
echo "\"Percipitation\":", json_encode($percipitation), ",";
echo "\"SnowDrop\":", json_encode($snowDrop), ",";
echo "\"Freeze\":", json_encode($freeze), ",";
echo "\"Rain\":", json_encode($rain), ",";
echo "\"Snow\":", json_encode($snow), ",";
echo "\"Hail\":", json_encode($hail), ",";
echo "\"Thunder\":", json_encode($thunder), ",";
echo "\"Tornado\":", json_encode($tornado), ",";
echo "\"CloudCoverage\":", json_encode($cloudCoverage), ",";
echo "\"WindDirection\":", json_encode($windDirection);
echo "}";
?>